# Generated by Django 3.0.4 on 2020-05-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('quantity', models.IntegerField(default=0)),
                ('minQuantity', models.IntegerField(default=0)),
                ('categoryId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Category')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.User')),
            ],
        ),
    ]
