# Generated by Django 3.0.4 on 2020-03-24 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20200324_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='filmId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.Film'),
            preserve_default=False,
        ),
    ]
